version: '3'
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/html

  app:
    build: ./docker/app
    volumes:
      - ./laravel:/var/www/html
    depends_on:
        - db

  db:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./docker/db/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: sample
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./.docker/minio/data:/export
    environment:
      MINIO_ACCESS_KEY: SEN2021INTERN
      MINIO_SECRET_KEY: JACKDANIELS
    command: server /export
  miniomc:
    build:
      context: ./docker/miniomc
    environment:
      - 'MINIO_ACCESS_KEY=SEN2021INTERN'
      - 'MINIO_SECRET_KEY=JACKDANIELS'
      - 'MINIO_BUCKET=sample'
    depends_on:
      - minio
